books/urls.py
from django.urls import path
from .views import home, BookCreate, BookUpdate, BookDelete

app_name = 'books'
urlpatterns = [
    path('create/', BookCreate.as_view(), name='create'),
    path('update/<int:pk>/', BookUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', BookDelete.as_view(), name='delete'),
    path('', home, name='home'),
]

http_head/urls.py
from django.urls import path
from .views import home

app_name = 'http_head'
urlpatterns = [
    path('', home, name='home'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('http_head/', include('http_head.urls')),
]

books/models.py
from django.db import models
from django.utils import timezone


class BookQuerySet(models.query.QuerySet):
    
    def sort(self, how_to='desc'):
        if how_to == 'desc':
            return self.order_by('publish_date')
        else:
            return self.order_by('-publish_date')
        
        
class BookManager(models.Manager):
    
    def get_queryset(self):
        return BookQuerySet(self.model, using=self._db)

    def sort(self, how_to='desc'):
        return self.get_queryset().sort(how_to)


class Book(models.Model):
    book_title = models.CharField(max_length=255, verbose_name='Название книги')
    authors_info = models.TextField(verbose_name='Информация об авторах')
    isbn = models.CharField(max_length=20, unique=True,
                            verbose_name='ISBN книги')
    price = models.DecimalField(max_digits=10, decimal_places=2, 
                                verbose_name='Цена книги')
    publish_date = models.DateField(default=timezone.now, 
                                    verbose_name='Дата публикации')
    objects = BookManager()
                                                    
    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'
        ordering = ['book_title']
        
    def __str__(self):
        return self.book_title

http_head/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField


class HttpHead(models.Model):
    data = JSONField()
    timestamp = models.DateField(auto_now_add=True)
    
    class Meta:
        verbose_name = 'Запрос к сайту'
        verbose_name_plural = 'Запросы к сайту'
        ordering = ['-timestamp']

    def __str__(self):
        return 'Запрос от {} '.format(self.timestamp)

books/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):
    book_title = forms.CharField(label='Название', required=True,
                                 widget=forms.TextInput(
                                        attrs={"class": 'form-control'}))
    authors_info = forms.CharField(label='Информация об авторах',
                                   widget=forms.TextInput(
                                        attrs={"class": 'form-control'}))
    isbn = forms.CharField(label='ISBN',
                           widget=forms.TextInput(
                               attrs={"class": 'form-control'}))
    price = forms.DecimalField(label='Цена', required=True,
                                     widget=forms.NumberInput(
                                         attrs={"class": 'form-control'}))
    publish_date = forms.CharField(label='Дата публикации',
                                   widget=forms.TextInput(
                                        attrs={"class": 'form-control datetimepicker3'}))

    class Meta(object):
        model = Book
        fields = ('book_title', 'authors_info', 'isbn', 'price', 'publish_date')

books/views.py
import logging
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView, UpdateView, DeleteView
from .models import Book
from .forms import BookForm
from django.contrib import messages

logger = logging.getLogger(__name__)


def home(request):
    sort = request.GET.get('sort', 'desc')
    if sort == 'desc':
        qs = Book.objects.sort()
    else:
        qs = Book.objects.sort('asc')
    context = {}
    context['objects_list'] = qs
    return render(request, 'books/home.html', context)
    
    
class BookCreate(SuccessMessageMixin, CreateView):
    model = Book
    form_class = BookForm
    template_name = 'books/create.html'
    success_url = reverse_lazy('books:home')
    success_message = "Книга была успешно создана!"
    
    def post(self, request, *args, **kwargs):
        logger.info('The book was created!')
        return super().post(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


class BookUpdate(SuccessMessageMixin, UpdateView):
    model = Book
    form_class = BookForm
    template_name = 'books/create.html'
    success_url = reverse_lazy('books:home')
    success_message = "Редактирование прошло успешно!"
    
    def post(self, request, *args, **kwargs):
        logger.info('The book was updated!')
        return super().post(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)
        

class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books:home')
        
    def get(self, request, *args, **kwargs):
        messages.success(request, 'Книга была успешно удалена!')
        logger.info('The book was deleted!')
        return self.post(request, *args, **kwargs)

http_head/views.py
from django.shortcuts import render
from .models import HttpHead
import json


def home(request):
    qs = HttpHead.objects.all()
    if qs.count() > 10:
        qs = qs[:10]
    data = []
    for q in qs:
        data.append(json.loads(q.data))
    context = {}
    context['objects_list'] = data
    return render(request, 'http_head/home.html', context)

books/templates/books/create.html
{% extends 'base.html' %}

{% block title %}Создание | Редактирование {% endblock %}

{% block content %}

    <h2 class=''><span>Книга</span></h2>
   
   <div class="row">
        <div class="col-6">
			<form action="" method="post" > {% csrf_token %}
				{{form.as_p}}
				<input type="submit" value="Сохранить">
			</form>
			<script type="text/javascript">
            $(function () {
                $('.datetimepicker3').datetimepicker({
                    format: 'YYYY-MM-DD'
                });
            });
        </script>
        </div>
    </div>

	
{% endblock %}


	
	
	

books/templates/books/home.html
{% extends 'base.html' %}

{% block title %}Книги {% endblock %}

{% block content %}

    <h2 class='text-center'><span>Книги</span></h2>
   
   <div class="row">
		<div class="col text-right">
		<a href="{%url 'admin:app_list' 'books' %}" >
				<button type="button" class='btn btn-info btn-sm' >
					Административная часть
				</button></a>
		</div>
        <div class="col-md-11 mx-auto">
			
			<hr>
			<table class="table table-striped">
				<thead>
                    <tr >
                        <th class="align-top" scope="col">Название книги</th>
                        <th class="align-top" scope="col">Информация об авторах</th>
                        <th class="align-top" scope="col">ISBN</th>
                        <th class="align-top" scope="col">Цена</th>
                        <th class="align-top" scope="col">Дата<br/> публикации <br/>
							<a href="{%url 'books:home' %}?sort=desc">-</a>/
							<a href="{%url 'books:home' %}?sort=asc">+</a></th>
						<th scope="col">&nbsp;</th>
						<th scope="col">&nbsp;</th>
                    </tr>
                </thead>
				<tbody>
				{% for object in objects_list %}
					<tr>
						<td>{{ object.book_title }}</td>
						<td>{{ object.authors_info }}</td>
						<td>{{ object.isbn }}</td>
						<td>{{ object.price }}</td>
						<td>{{ object.publish_date| date:"d/m/Y" }}</td>
						<td>
							<a href="{%url 'books:update' pk=object.pk %}">
								<button type="button" class='btn btn-success btn-sm' >
									Редактировать</button></a>
						</td>
						<td>
							<a href="{%url 'books:delete' pk=object.pk %}">
								<button type="button" class='btn btn-danger btn-sm' >
									Удалить</button></a>
						</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
    </div>
	
	


	{% endblock %}
	
	
									
	

http_head/templates/http_head/home.html
{% extends 'base.html' %}

{% block title %}Requests {% endblock %}

{% block content %}

    <h2 class='text-center'><span>requests.META</span></h2>
   
   <div class="row">
        <div class="col-md-11 mx-auto">
			
				{% for object in objects_list %}
					<h4> Request #{{forloop.counter}}</h4>
					<table class="table table-striped">
					
						<tbody>
							{% for key, value in object.items %}	
							<tr>
								<td>{{ key }}</td>
								<td>{{ value }}</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
					<br/>
					<hr>
				{% endfor %}
				
		</div>
    </div>
	

	{% endblock %}
	
	
									
	

templates/base.html
{% url 'books:home' as home_url %}
{% url 'books:create' as create_url %}
{% url 'http_head:home' as req_url %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="http://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css">
	<!-- <link rel="stylesheet" href="http://getbootstrap.com/docs/4.1/examples/starter-template/starter-template.css"> -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
	<script src="https://cdn.jsdelivr.net/bootstrap/3.3.0/js/bootstrap.min.js"></script>
	<script src="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.0.0/js/bootstrap-datetimepicker.min.js"></script>
    <title>{% block title  %}  {% endblock %}</title>
  </head>
  <body>
	<div class="container">
	  <nav class="navbar navbar-expand-md navbar-dark  " style="background-color: #999;">
		  <a class="navbar-brand" href="{% url 'books:home' %}">BookStore</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		  </button>

		  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
			<ul class="navbar-nav ml-auto">
			  
			  <li class="nav-item {% if request.path == home_url %}active{% endif %}">
				<a class="nav-link" href="{% url 'books:home' %}">Книги</a>
			  </li>
			   <li class="nav-item {% if request.path == create_url %}active{% endif %}">
				<a class="nav-link " href="{%url 'books:create' %}">Создать</a>
			  </li>
			  <li class="nav-item {% if request.path == req_url %}active{% endif %}">
				<a class="nav-link " href="{%url 'http_head:home' %}">Запросы к сайту</a>
			  </li>
			</ul>
			<!-- <form class="form-inline my-2 my-lg-0">
			  <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
			  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
			</form> -->
		  </div>
		</nav> 
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-8 mx-auto">
			  {% if messages %}
				{% for message in messages %}
				  {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
					<div class="alert alert-danger messages">
					  <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
						Внимание!  {{ message }}<br/>
					  </span>
					</div>
				  {%else %} 
					<div class="alert alert-success messages">
					  <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
						{{ message }}<br/>
					  </span>
					</div>
				  {% endif %}
				{% endfor %}
			  {% endif %}
			</div>
		</div>
     </div>
	 <div  class="container my-5">
	{% block content  %} {% endblock %}
    </div>
	<footer class="footer fixed-bottom my-3 text-center">
      <div class="container">
		{% now "Y" as current_year %}
		{%if current_year == '2018'%}
			<span class="text-muted">Copyright {{ current_year }}</span>
		{% else %}
			<span class="text-muted">Copyright '2018' - {{ current_year }}</span>
		{% endif %}
      </div>
    </footer>
    
  </body>
</html>